name: pppp
channels:
  - conda-forge
  - bioconda
dependencies:
  - snakemake
  - jinja2
  - matplotlib
  - graphviz
  - bcftools 
  - samtools 
  - bwa 
  - pygments
  - pysam
  - minimap2
  - biopython
  - Nanoplot
  - cutadapt
  - medaka
  - gzip
  - edlib